version: "3.0"
services:
  redis:
    image: redis:5.0.4
    ports:
      - "6379:6379"

  fam100:
    build: .
    command: /fam100 -quorum 2
    depends_on:
      - redis
    volumes:
      - "./qna:/qna"
    environment:
      #Kisanak100
      TELEGRAM_KEY: "664559956:AAEu-OdZJAoIJVINki-7KNd2cOWpvC5aj98"
      
      #Sanak100
      #TELEGRAM_KEY: "708555747:AAGXERJs57scLc2HNpKdz5aCj_hZsCvzdKg"
      QUESTION_DB_PATH: "qna/questions.txt"
      REDIS_ADDR: "redis:6379"

